// Code generated by Wire. DO NOT EDIT.
// 這個檔案模擬 wire 工具生成的結果
// 真正使用時執行：go install github.com/google/wire/cmd/wire@latest && wire ./internal/di/

//go:generate go run -mod=mod github.com/google/wire/cmd/wire

package di

import (
	"ticket-system/pkg/config"

	"go.opentelemetry.io/otel/trace"
)

// InitializeApp 建立整個應用程式的依賴樹
// 此函式由 Wire 根據 wire.go 的 Injector 定義自動生成
func InitializeApp(cfg *config.Config, tracer trace.Tracer) (*App, func(), error) {
	// 1. 基礎設施
	db, err := ProvideDB(cfg)
	if err != nil {
		return nil, nil, err
	}

	redisClient, err := ProvideRedis(cfg)
	if err != nil {
		return nil, nil, err
	}

	broker := ProvideBroker()
	hub := ProvideHub()

	// 2. gRPC
	grpcComps, err := ProvideGRPC()
	if err != nil {
		return nil, nil, err
	}

	breaker := ProvideBreaker()

	// 3. Repository
	eventRepo := ProvideEventRepo(db)
	orderWriteRepo := ProvideOrderWriteRepo(db)
	orderReadRepo := ProvideOrderReadRepo(db)

	// 4. Usecase
	ticketUsecase := ProvideTicketUsecase(redisClient, eventRepo, orderWriteRepo, orderReadRepo, broker, tracer)

	// 5. Handler
	ticketHandler := ProvideTicketHandler(ticketUsecase)
	wsHandler := ProvideWSHandler(hub)

	// 6. Worker
	paymentWorker := ProvidePaymentWorker(broker, orderWriteRepo, grpcComps, breaker, hub, tracer)
	stockBroadcaster := ProvideStockBroadcaster(broker, hub)

	// Cleanup 函式（關閉 gRPC、Broker 等）
	cleanup := func() {
		grpcComps.Cleanup()
		broker.Close()
	}

	app := &App{
		DB:               db,
		Redis:            redisClient,
		Broker:           broker,
		Hub:              hub,
		GRPC:             grpcComps,
		TicketUsecase:    ticketUsecase,
		TicketHandler:    ticketHandler,
		WSHandler:        wsHandler,
		PaymentWorker:    paymentWorker,
		StockBroadcaster: stockBroadcaster,
	}

	return app, cleanup, nil
}
