// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire

package di

import (
	"ticket-system/pkg/config"

	"go.opentelemetry.io/otel/trace"
)

func InitializeApp(cfg *config.Config, tracer trace.Tracer) (*App, func(), error) {
	db, err := ProvideDB(cfg)
	if err != nil {
		return nil, nil, err
	}

	stock := ProvideStockStore(cfg)
	broker := ProvideBroker()
	hub := ProvideHub()

	grpcComps, err := ProvideGRPC()
	if err != nil {
		return nil, nil, err
	}

	breaker := ProvideBreaker()

	eventRepo := ProvideEventRepo(db)
	orderWriteRepo := ProvideOrderWriteRepo(db)
	orderReadRepo := ProvideOrderReadRepo(db)

	ticketUsecase := ProvideTicketUsecase(stock, eventRepo, orderWriteRepo, orderReadRepo, broker, tracer)
	ticketHandler := ProvideTicketHandler(ticketUsecase)
	wsHandler := ProvideWSHandler(hub)

	paymentWorker := ProvidePaymentWorker(broker, orderWriteRepo, grpcComps, breaker, hub, tracer)
	stockBroadcaster := ProvideStockBroadcaster(broker, hub)

	cleanup := func() {
		grpcComps.Cleanup()
		broker.Close()
	}

	app := &App{
		DB:               db,
		Stock:            stock,
		Broker:           broker,
		Hub:              hub,
		GRPC:             grpcComps,
		TicketUsecase:    ticketUsecase,
		TicketHandler:    ticketHandler,
		WSHandler:        wsHandler,
		PaymentWorker:    paymentWorker,
		StockBroadcaster: stockBroadcaster,
	}

	return app, cleanup, nil
}
